language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install -y ant patch build-essential file

install:
  - ./build.sh -d `cat NEOLOGD_VERSION_DATE`

notifications:
  email: false
